theme: jekyll-theme-cayman
title: CompiledSanity Personal Finance Sheets
descrption: Automated Finance tools designed to make life easy for you, give you a wholistic glimpse of your financial position and if you're a stats nerd tell you where you're heading.
